In [1]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
print("FIRST 5 ROWS:")
display(df.head())
print("\nLAST 5 ROWS:")
display(df.tail())
print("\nDATASET SIZE:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("\nCOLUMN NAMES:")
print(df.columns.tolist())
print("\nDATASET INFORMATION:")
df.info()
print("\nMISSING VALUES:")
print(df.isnull().sum())
print("\nDUPLICATE ROWS:")
print(df.duplicated().sum())
print("\nSTATISTICAL SUMMARY:")
display(df.describe())
print("\nDATA TYPES:")
print(df.dtypes)
print("\nDataset loaded successfully!")

FIRST 5 ROWS:

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

LAST 5 ROWS:

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

DATASET SIZE:
Rows: 100000
Columns: 9

COLUMN NAMES:
['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes']

DATASET INFORMATION:
<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  str
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  str
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), str(2)
memory usage: 6.9 MB

MISSING VALUES:
gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

DUPLICATE ROWS:
3854

STATISTICAL SUMMARY:

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

DATA TYPES:
gender                     str
age                    float64
hypertension             int64
heart_disease            int64
smoking_history            str
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

Dataset loaded successfully!

In [5]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
print("First 5 rows:")
display(df.head())

First 5 rows:

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [8]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
display("last 5 rows:")
df.tail()

'last 5 rows:'

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [10]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.shape

(100000, 9)

In [12]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.dtypes

gender                     str
age                    float64
hypertension             int64
heart_disease            int64
smoking_history            str
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

In [13]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='str')

In [15]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  str
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  str
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), str(2)
memory usage: 6.9 MB

In [16]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [26]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["diabetes"].isnull()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: diabetes, Length: 100000, dtype: bool

In [27]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"].min()

np.float64(0.08)

In [28]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"].max()

np.float64(80.0)

In [29]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"].sum()

np.float64(4188585.5999999996)

In [30]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"].unique()

array([80.  , 54.  , 28.  , 36.  , 76.  , 20.  , 44.  , 79.  , 42.  ,
       32.  , 53.  , 78.  , 67.  , 15.  , 37.  , 40.  ,  5.  , 69.  ,
       72.  ,  4.  , 30.  , 45.  , 43.  , 50.  , 41.  , 26.  , 34.  ,
       73.  , 77.  , 66.  , 29.  , 60.  , 38.  ,  3.  , 57.  , 74.  ,
       19.  , 46.  , 21.  , 59.  , 27.  , 13.  , 56.  ,  2.  ,  7.  ,
       11.  ,  6.  , 55.  ,  9.  , 62.  , 47.  , 12.  , 68.  , 75.  ,
       22.  , 58.  , 18.  , 24.  , 17.  , 25.  ,  0.08, 33.  , 16.  ,
       61.  , 31.  ,  8.  , 49.  , 39.  , 65.  , 14.  , 70.  ,  0.56,
       48.  , 51.  , 71.  ,  0.88, 64.  , 63.  , 52.  ,  0.16, 10.  ,
       35.  , 23.  ,  0.64,  1.16,  1.64,  0.72,  1.88,  1.32,  0.8 ,
        1.24,  1.  ,  1.8 ,  0.48,  1.56,  1.08,  0.24,  1.4 ,  0.4 ,
        0.32,  1.72,  1.48])

In [31]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"].mean()

np.float64(41.885856)

In [32]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"].mode()

0    80.0
Name: age, dtype: float64

In [33]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"].var()

np.float64(507.008077804042)

In [34]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"].median()

np.float64(43.0)

In [35]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"].dropna()

0        80.0
1        54.0
2        28.0
3        36.0
4        76.0
         ...
99995    80.0
99996     2.0
99997    66.0
99998    24.0
99999    57.0
Name: age, Length: 100000, dtype: float64

In [48]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.duplicated().sum()

np.int64(3854)

In [39]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"]

0        80.0
1        54.0
2        28.0
3        36.0
4        76.0
         ...
99995    80.0
99996     2.0
99997    66.0
99998    24.0
99999    57.0
Name: age, Length: 100000, dtype: float64

In [45]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.iloc[11:21]

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
11,Female,54.0,0,0,former,54.70,6.0,100,0
12,Female,78.0,0,0,former,36.05,5.0,130,0
13,Female,67.0,0,0,never,25.69,5.8,200,0
14,Female,76.0,0,0,No Info,27.32,5.0,160,0
15,Male,78.0,0,0,No Info,27.32,6.6,126,0
16,Male,15.0,0,0,never,30.36,6.1,200,0
17,Female,42.0,0,0,never,24.48,5.7,158,0
18,Female,42.0,0,0,No Info,27.32,5.7,80,0
19,Male,37.0,0,0,ever,25.72,3.5,159,0
20,Male,40.0,0,0,current,36.38,6.0,90,0

In [47]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df["age"].isnull().sum

<bound method Series.sum of 0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: age, Length: 100000, dtype: bool>

In [49]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.sort_values("gender")

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
58000,Female,42.0,0,0,former,34.30,6.1,155,0
57999,Female,66.0,0,0,No Info,27.32,4.5,100,0
57998,Female,28.0,0,0,former,32.16,4.0,90,0
57996,Female,11.0,0,0,No Info,14.09,5.7,160,0
...,...,...,...,...,...,...,...,...,...
33805,Other,45.0,0,0,never,27.32,4.0,159,0
75734,Other,24.0,0,0,not current,22.86,6.2,160,0
34929,Other,47.0,0,0,never,36.76,6.6,90,0
16702,Other,39.0,0,0,not current,31.24,6.2,85,0
12669,Other,10.0,0,0,not current,14.09,5.0,140,0

In [51]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.drop_duplicates()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99994,Female,36.0,0,0,No Info,24.60,4.8,145,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [58]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df[["gender","age","bmi"]].tail()

       gender   age    bmi
99995  Female  80.0  27.32
99996  Female   2.0  17.37
99997    Male  66.0  27.83
99998  Female  24.0  35.42
99999  Female  57.0  22.43

In [56]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df[df["age"]>30].head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
6,Female,44.0,0,0,never,19.31,6.5,200,1

In [61]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.rename(columns={"bmi":"body mass index"}).head()

,gender,age,hypertension,heart_disease,smoking_history,body mass index,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [62]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.drop("heart_disease",axis=1)

,gender,age,hypertension,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,never,25.19,6.6,140,0
1,Female,54.0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,never,27.32,5.7,158,0
3,Female,36.0,0,current,23.45,5.0,155,0
4,Male,76.0,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,current,22.43,6.6,90,0

In [76]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.groupby("gender").count()

,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
gender,,,,,,,,
Female,58552,58552,58552,58552,58552,58552,58552,58552
Male,41430,41430,41430,41430,41430,41430,41430,41430
Other,18,18,18,18,18,18,18,18

In [78]:
import pandas as pd
file_path = r"C:\Users\user\Desktop\diabetes_prediction_dataset.csv"
df = pd.read_csv(file_path)
df.groupby("bmi")["diabetes"].mean()

bmi
10.01    0.0
10.08    0.0
10.14    0.0
10.19    0.0
10.21    0.0
        ...
88.72    1.0
88.76    0.0
91.82    0.0
95.22    0.0
95.69    0.0
Name: diabetes, Length: 4247, dtype: float64